### ISSUE TITLE
Custom framerate?

### ISSUE THREAD

**Issue by shiffman** [WenheLI/p5.gif#7]
The frame rate I don't believe is changing if I pass in a custom value in config, I am trying:

```javascript
  recorder = p5Gif.capture({framerate: 60});
```

But the GIF appears to stick with the 10 FPS default?

Full code: https://editor.p5js.org/codingtrain/sketches/WfEih8mL7

**Comment by fffiloni** [comment]
I found a way to overwrite settings : 
After you initialized the recorder, set custom settings like this

```
recorder = p5Gif.capture();

 recorder.settings.width = 200;
 recorder.settings.height = 200;
 recorder.settings.framerate = 12;
```

This will work, until changes are made by the developers

**Comment by WenheLI** [comment]
Actually, we currently forbid the framerate going beyond 20 fps. It is a concern of the run-time performance. If the fps is large, the time for saving gif will be quite long. We will see if we can tune up the fps restriction.

**Comment by WenheLI** [comment]
@shiffman @fffiloni  Thanks for your help. The custom framerate problem has been solved. I limited the upper framerate to 30 right now. Do you think it is still small? We originally thought a large framerate will make the browser crash.

**Comment by fffiloni** [comment]
Hello !

It seems that the custom framerate is still not changing. In the recorder.settings.framerate we see it has changed, but then the gif that is created do not take this number. 

My gif, once downloaded, are always at the same rate : 10. 

Thanks for your help !

**Comment by fffiloni** [comment]
maybe it is something involved with the `delay`value  on the gif export ?

**Comment by fffiloni** [comment]
i moved my last question into a new issue : #16 
because i think its a new features request  ;)
